# -*- coding: utf-8 -*-
"""project.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HLc1KDWQT4THOTw4dNBZyyXtJQ5fyEkd
"""

pip install pyspark

import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *

spark= SparkSession.builder.master('local').appName('Test').getOrCreate()

from google.colab import drive
drive.mount('/content/drive')

df= spark.read.format('csv').option('header',True).load('/content/IEG_CLRR_Ratings_Q4FY22.1.csv')

df_rating = spark.read.format('csv').option('header',True).load('/content/IEG_ICRR-PPAR_Ratings_2023-08-01.1.csv')

df_anual_stacked=spark.read.format('csv').option('header',True).load('/content/annual_stacked_data.csv')

df_anual_stacked.show()

df.show()

df_rating.show()

df=df.na.fill(" ")
df.show()

df_rating=df_rating.na.fill(" ")
df_rating.show()

df_anual_stacked=df_anual_stacked.na.fill(" ")
df_anual_stacked.show()

df.count()

df.drop_duplicates()

df.count()

df=df.na.drop(how="any")

df.count()

df_rating.count()

df_rating.drop_duplicates()

df_rating.count()

df_rating.na.drop()

df_rating.count()

df_rating.show()

for i in df:
  print(i)

for j in df_rating:
  print(j)

df1=df.groupBy('Title','FY','Country Income Group','Review FY','IEG Development Outcome Rating','IEG WBG Performance Rating','Document URL').count()

newdf1=df1.join(df_rating)

newdf1.dropDuplicates()

newdf1.na.drop(how="any")

df_anual_stacked.dropDuplicates()

final_df=newdf1.join(df_anual_stacked)

final_df.drop_duplicates()

final_df.show()

finaal_df=final_df.na.drop(how='any', thresh=None, subset=None)
finaal_df.show()

finaal_df=finaal_df.drop("IEG Bank Performance Ratings","IEG Quality at Entry Ratings","IEG Quality of Supervision Ratings","Country Lending Group","Project Volume")

finaal_df.show()

finaal_df.dropDuplicates()

